version: "3.7"

services:
  internetapp:
    image: internetapp:latest
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 9090:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306

  mysqldb:
    image: mysql:latest
    volumes:
      - exam-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: internet
    ports:
      - 3307:3306

volumes:
  exam-mysql-data: